// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SensorControl struct {
	ID              int32
	SensorType      string
	Mode            string
	ManualUntil     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ManualBoolValue pgtype.Bool
	ManualIntValue  pgtype.Int4
}

type SensorReading struct {
	ID         int64
	SensorType string
	Value      float64
	Timestamp  pgtype.Timestamptz
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
