// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           int32
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}
