services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env.local
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
      - DB_SSLMODE=disable
      - JWT_SECRET=UuJyZbqrxWcYnGKEgTqRhG7TfdBToKs3kO4OxbHd3Gs=
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  postgres_data:
