services:
  app:
    image: lulzshadowwalker/green-backend:prod
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
      - DB_SSLMODE=disable
      - JWT_SECRET=UuJyZbqrxWcYnGKEgTqRhG7TfdBToKs3kO4OxbHd3Gs=
    depends_on:
      - db
    networks:
      # - backend
      # - loki
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green.rule=Host(`green.lulzie.online`)"
      - "traefik.http.routers.green.entrypoints=websecure"
      - "traefik.http.routers.green.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    restart: always

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      # - backend
      - proxy

  adminer:
    image: adminer:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green_adminer.rule=Host(`adminer.green.lulzie.online`)"
      - "traefik.http.routers.green_adminer.entrypoints=websecure"
      - "traefik.http.routers.green_admin.tls.certresolver=myresolver"
    depends_on:
      - db
    networks:
      # - backend
      - proxy
  #
  #  loki:
  #    image: grafana/loki:2.9.3
  #    volumes:
  #      - ~/dev/docker-volumes/loki:/etc/loki
  #    ports:
  #      - "3100:3100"
  #    restart: unless-stopped
  #    command: -config.file=/etc/loki/loki-config.yml
  #    networks:
  #      - loki
  #
  #  promtail:
  #    image: grafana/promtail:2.4.0
  #    volumes:
  #      - /var/log:/var/log
  #      - ~/dev/docker-volumes/promtail:/etc/promtail
  #    # ports:
  #    #   - "1514:1514" # this is only needed if you are going to send syslogs
  #    restart: unless-stopped
  #    command: -config.file=/etc/promtail/promtail-config.yml
  #    networks:
  #      - loki
  #
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ~/volumes/grafana:/var/lib/grafana
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green_grafana.rule=Host(`grafana.green.lulzie.online`)"
      - "traefik.http.routers.green_grafana.entrypoints=websecure"
      - "traefik.http.routers.green_grafana.tls.certresolver=myresolver"
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "15"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  letsencrypt:

networks:
  # loki:
  # backend:
  proxy:
    external: true
